version: '3.7'

services:
    webserver:
        build: ./Docker/
        ports:
            - "80:80"
        working_dir: /var/www/
        volumes:
            - .:/var/www/
        depends_on:
            - database
    database:
        image: mariadb
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 1
            MYSQL_DATABASE: divineat
            MYSQL_USER: divineat
            MYSQL_PASSWORD: 64SSmuA
        ports:
            - "3306:3306"
    mail:
        image: mailhog/mailhog
        ports:
            - 1025:1025
            - 8025:8025
