/:
  controller: default
  action: default

/test/yves:
  controller: default
  action: default


/ajout-utilisateur:
  controller: "user"
  action: "add"

/utilisateur:
  controller: "user"
  action: "default"

/se-connecter:
  controller: "user"
  action: "login"

/s-inscrire:
  controller: "user"
  action: "register"

/mot-de-passe-oublie:
  controller: "user"
  action: "forgotPwd"


/phps2:
  controller: "user"
  action: "get"

/phps2-json:
  controller: "user"
  action: "json"

  /user:
    controller: "user"
    action: "default"

    /first-user:
      controller: "user"
      action: "getFirstUser"
      /error:
        controller: "error"
        action: "displayError"
          







