/:
  controller: Default
  action: default

/ajout-utilisateur:
  controller: "User"
  action: "add"

/utilisateur:
  controller: "User"
  action: "default"

/login:
  controller: "User"
  action: "login"

/register:
  controller: "User"
  action: "register"

/forgotPwd:
  controller: "User"
  action: "forgotPwd"

/test:
  controller: "Test"
  action: "default"

/menus:
  controller: "Menu"
  action: "index"

/add_menu:
  controller: "Menu"
  action: "add"
