/:
  controller: Default
  action: default

/ajout-utilisateur:
  controller: "User"
  action: "add"

/utilisateur:
  controller: "User"
  action: "default"

/se-connecter:
  controller: "User"
  action: "login"

/s-inscrire:
  controller: "User"
  action: "register"

/mot-de-passe-oublie:
  controller: "User"
  action: "forgotPwd"

/test:
  controller: "Test"
  action: "default"

/menus:
  controller: "Menu"
  action: "index"

/pageBuilder:
  controller: "PageBuilder"
  action: "default"

/pageBuilderAddModal:
  controller: "PageBuilder"
  action: "addTextAreaEditor"
