/:
  controller: default
  action: default

/test/yves:
  controller: default
  action: default


/ajout-utilisateur:
  controller: "user"
  action: "add"

/utilisateur:
  controller: "user"
  action: "default"

/login:
  controller: "user"
  action: "login"

/register:
  controller: "user"
  action: "register"

/forgotpwd:
  controller: "user"
  action: "forgotpwd"

/phps2-json:
  controller: "user"
  action: "json"









